#!/usr/bin/env bash
# Forked from https://github.com/dasgeekchannel/AutoInstallBashScripts
# Adapted for Drupal Developers on Ubunutu

## Define Temporary Directory Location - "ais" stands for "Auto Install Script"
tmp_dir=/tmp/ais

## Define some variables to make it less typing
install='apt install -y'
update='apt update'
user=$USER


## Check if snapd has been installed just in case
check_snap () {
	if ! [ -e /usr/lib/snapd ] ; then
		$install snapd -y
	fi
}

## Start script
if [[ $EUID -ne 0 ]]; then
   	echo "This script must be run as root type: sudo ./installapps" 
   	exit 1
else
	#Update and Upgrade
	echo "Updating and Upgrading"
	$update

	echo "Creating temporary folder"
	mkdir $tmp_dir

	$install dialog 
	cmd=(dialog --title "StephenCross Installer" --separate-output --checklist "Please Select Software You Want To Install:" 22 80 16)
	options=(
		#A "<----Category: Software Repositories---->" on
			1 "Repo: Install Flatpak" off
			2 "Repo: Install Snaps" off
	        3 "Comm: Zoom Meeting Client" off
	        4 "Comm: Telegram (Snap)" off 
	        5 "Browser:	Google Chrome" off
	       	6 "Browser:	Firefox Browser" off     	
		    7 "Drupal: Virtualbox" off
			8 "Drupal: Docker(CE)" off
            9 "Drupal: Visual Studio Code" off
		X "Post Install Auto Clean Up & Update" off)
		choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
		clear
		for choice in $choices
		do
		    case $choice in
# Section A ------------repos----------------------
	        1)	
				#Install Flatpak Repo (Software Repository)
				echo "Installing Flatpak Repository"
				$install flatpak -y
				sleep 1
				;;

			2)	
				#Install Snap Repository (Software Repository)
				echo "Installing Snap Repository"
				check_snap
				sleep 1
				;;

			3)
				#Zoom
				echo "Installing Zoom Meeting Client"
				echo "Installing dependency first"				
				$install libxcb-xtest0
				wget https://zoom.us/client/latest/zoom_amd64.deb -O $tmp_dir/zoom_install.deb
				dpkg -i $tmp_dir/zoom_install.deb
				sleep 1
				;;
				
			4)
				#Telegram
				echo "Telegram Snap"
				check_snap
				snap install telegram-desktop
				sleep 1
				;;

			5)
				#Chrome
				echo "Installing Google Chrome"
				if ! [ -e /etc/apt/sources.list.d/google-chrome.list ]; then
					wget -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
					echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
				fi
				apt update 
				$install google-chrome-stable 
				;;

			6)
				#Firefox Browser
				echo "Firefox"
				$install firefox 
				;;

    		7)	
    			#Virtualbox
				echo "Installing Virtualbox"
				$install virtualbox 
				sleep 1
				;;

				
			8) #Docker
				echo "Installing Docker CE"
			 	## Setup apt to use a repository over https
				$update
    			$install apt-transport-https
				sleep 2
    			$install ca-certificates 
    			sleep 2
				$install curl 
    			sleep 2
				$install gnupg-agent 
    			sleep 2
				$install software-properties-common
				sleep 2
				## Docker
                curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
                add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu disco stable" -y
                apt-get update -y
                apt-get install docker-ce
				sleep 1
				;;
        
			9)
				#Visual Studio Code
				echo "Visual Studio Code"
				wget -O $tmp_dir/visualstudio.deb https://go.microsoft.com/fwlink/?LinkID=760868
				dpkg -i $tmp_dir/visualstudio.deb
				sleep 1
				;;
	
			X)  
				#Clean up
				echo "Cleaning up"
				$update
				apt autoremove -y
				rm -rf $tmp_dir
				;;
	
	    esac
	done
fi
